%make_ECC_figures_gl_sadra.m
%Description:
%	Makes the figures used in the ECC 2020 paper, but using the Great Lakes Cluster at the University of Michigan.

cd ../../..

%mptopt('lpsolver','mosek')

%Create the images for simple belief graph things
%ot1 = observer_tests(56,{'true'});

results = observer_tests([60,60,60], ...
			{[' ''c_sq'', 2,1 ,' ...
				' ''L'' ,Language([1,2,2,1],[1,2,1,1],[1,1,2,1]),' ...
				' ''disturb_bounds'',0.35,0.2,' ...
				' ''eta_u'', 50 , ''UseProjection'', false '], ...
			[' 	''c_sq'', 2,1 ,' ...
				' ''L'' ,Language([1,2,2,1,1],[1,2,1,1,1],[1,1,2,1,1]),' ...
				' ''disturb_bounds'',0.35,0.2,' ...
				' ''eta_u'', 50 , ''UseProjection'', false '], ...
			[' 	''c_sq'', 2,1 ,' ...
			 	' ''L'' ,Language([1,2,2,1,1,1],[1,2,1,1,1,1],[1,1,2,1,1,1]),' ...
			 	' ''disturb_bounds'',0.35,0.2,' ...
			 	' ''eta_u'', 50 , ''UseProjection'', false ']})


%Saving the 'results' variable
cd data/ecc2020

end_time = datestr(now);
file_suffix = replace(end_time,' ','.');
file_suffix = replace(file_suffix,':','-');

savefilename = [ 'eccfig_data.mat'   ];

save(savefilename)